---
- name: Manage Gateway Authenticators Block
  no_log: "{{ gateway_authenticators_secure_logging }}"
  block:
    - name: Authenticators | Configuration
      ansible.platform.authenticator:
        name: "{{ __gateway_authenticators_item.name | mandatory }}"
        new_name: "{{ __gateway_authenticators_item.new_name | default(omit) }}"
        slug: "{{ __gateway_authenticators_item.slug | default(omit) }}"
        enabled: "{{ __gateway_authenticators_item.enabled | default(omit) }}"
        create_objects: "{{ __gateway_authenticators_item.create_objects | default(omit) }}"
        remove_users: "{{ __gateway_authenticators_item.remove_users | default(omit) }}"
        configuration: "{{ __gateway_authenticators_item.configuration | default(omit) }}"
        auto_migrate_users_to: "{{ __gateway_authenticators_item.auto_migrate_users_to | default(omit) }}"
        type: "{{ __gateway_authenticators_item.type | default(omit) }}"
        order: "{{ __gateway_authenticators_item.order | default(omit) }}"
        state: "{{ __gateway_authenticators_item.state | default(platform_state | default(omit, true)) }}"

        # Role Standard Options
        gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
        gateway_username: "{{ aap_username | default(omit, true) }}"
        gateway_password: "{{ aap_password | default(omit, true) }}"
        gateway_token: "{{ aap_token | default(omit, true) }}"
        gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ gateway_authenticators }}"
      loop_control:
        loop_var: __gateway_authenticators_item
        label: "{{ __operation.verb }} AAP Platform Authenticators {{ __gateway_authenticators_item.name }}"
        pause: "{{ gateway_authenticators_loop_delay }}"
      ignore_errors: "{{ aap_configuration_collect_logs | default(false) | bool }}"
      register: __gateway_authenticators_job_result
      vars:
        __operation: "{{ operation_translate[__gateway_authenticators_item.state | default(platform_state) | default('present')] }}"

    - name: Authenticators | Collect errors
      when: __gateway_authenticators_job_result_item is failed
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_sync_status
      loop: "{{ __gateway_authenticators_job_result.results }}"
      loop_control:
        loop_var: __gateway_authenticators_job_result_item
        label: "{{ __operation.verb }} AAP Platform Authenticators {{ __gateway_authenticators_job_result_item.__gateway_authenticators_item.name }} | Collect errors"
      vars:
        css_result: "{{ __gateway_authenticators_job_result_item }}"
        css_secure_logging: "{{ gateway_authenticators_secure_logging }}"
        css_error_list_var_name: "gateway_authenticators_errors"
        __operation: "{{ operation_translate[__gateway_authenticators_job_result_item.__gateway_authenticators_item.state | default(platform_state) | default('present')] }}"
...
